apiVersion: v1
kind: Service

metadata:
  name: enterprise-release-api
  namespace: enterprise-release

spec:
  selector:
    app: enterprise-release-api

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

  type: LoadBalancer